### ISSUE TITLE
The testflight build didn't seem to upload

### ISSUE THREAD

**Issue by sean-hill** [jbavari/cordova-deploy#8]
After providing my testflight `app_token` and `team_token` and getting

```
Uploading iOS to TestFlight
Upload iOS to TestFlight completed
```

My testflight looks like this...

![screen shot 2015-01-11 at 6 50 20 pm](https://cloud.githubusercontent.com/assets/1205866/5698120/c755ae92-99c2-11e4-8f47-3f4ae474ddbf.png)

I'm so sad that my app didn't upload :) Any ideas why?

**Comment by javiercr** [comment]
Same problem here :( are we missing something?

**Comment by jbavari** [comment]
I'm thinking what is happening is Apple is closing down TestFlight API, as they had just sent out an email stating you now are required to use iTunes Connect. This project will probably cease to exist.
